### ISSUE TITLE
[Dúvida] Qual vertice ele utiliza como primeiro?

### ISSUE THREAD

**Issue by kylefelipe** [lcoandrade/AzimuthDistanceCalculator#10]
Boa tarde!
Essa dúvida surgiu na seguinte thread do grupo [Qgis Brasil](https://groups.google.com/forum/#!topic/qgisbrasil/YEI8olEMkB8) o usuário queria saber qual vértice é utilizado como primeiro.. se é o mais ao norte ou algum outro.

**Comment by lcoandrade** [comment]
É o vértice mais ao norte.
